### PR TITLE
Issue 208 Add operator webhook configuration name

### LINKED ISSUE #208: Rename the mutating webhook configuration
The operator registers itself as a webhook, but doesn't set a name for the webhook configuration.  As a result, a default name is used, which could conflict with other webhooks in the system.

**Expected:**
```
$ kubectl get mutatingwebhookconfiguration
NAME                                     CREATED AT
pravega-operator                         2019-06-06T00:37:37Z
```

**Actual:**
```
$ kubectl get mutatingwebhookconfiguration
NAME                                     CREATED AT
mutating-webhook-configuration           2019-06-06T00:37:37Z
```

To fix, adjust the `webhook.BootstrapOptions` (in `add_webhook.go`) to set the
`MutatingWebhookConfigName` to `pravega-operator`.

### PR DESCRIPTION
**Pull request by pbelgundi**
### Change log description
The Pravega Operator creates a webhook for managing upgrades.
Webhook Name and WebhookConfiguration Name both have  not been set in the code which causes defaults to be used for these names. This can lead to issues if same namespace has multiple webhooks using defaults. 

### Purpose of the change
Fixes #208

### What the code does
Added code to specify, 'webhook name' when creating the webhook using controller-runtime builder and 'webhook configuration name' in webhook.BootstrapOptions when creating the webhook server. However, could not find any option to specify the "webhookConfigurationName" when creating the webhook using builder.

### How to verify it
Unit Tests and manual testing.

### CODE REVIEW

**Comment by EronWright** [comment]
This looks good to me, could you post the output from `kubectl get mutatingwebhookconfiguration` o confirm.

**Comment by pbelgundi** [comment]
Output after deploying operator with this fix:
```
pbelgundi@ubuntu:~$ kubectl get mutatingwebhookconfiguration
NAME                             CREATED AT
pravega-upgrade-webhook-config   2019-07-12T04:01:07Z
```

```
pbelgundi@ubuntu:~$  k describe mutatingwebhookconfiguration pravega-upgrade-webhook-config
Name:         pravega-upgrade-webhook-config
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  admissionregistration.k8s.io/v1beta1
Kind:         MutatingWebhookConfiguration
Metadata:
  Creation Timestamp:  2019-07-12T04:01:07Z
  Generation:          1
  Resource Version:    1204104
  Self Link:           /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations/pravega-upgrade-webhook-config
  UID:                 ad3bc5f5-a459-11e9-bed4-005056bf412f
Webhooks:
  Client Config:
    Ca Bundle:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwakNDQWJxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFhTVJnd0ZnWURWUVFERXc5M1pXSm8KYjI5ckxXTmxjblF0WTJFd0hoY05NVGt3TnpFeU1EUXdNVEEzV2hjTk1qa3dOekE1TURRd01UQTNXakFhTVJndwpGZ1lEVlFRREV3OTNaV0pvYjI5ckxXTmxjblF0WTJFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFEZnNZeWY4M2dKL0FwZzNENEJlQUg3d1hTV2ppb2hUZTh3NE9vN1FHWmRBNFM0M2d4NVFWT3UKYnpqcVRvanNoaHpQK1JrTWgxNkpVR1ZlRlErNk1jbFY5SE9tZTFzS0EyOHo0Vkd3NEZSb041TXRBWnhpUGtzawpYL0UwSjlPdXY2bDlZb1RUWitGa0xYZ3Q5eTFMQU52ZXFRSmJ0RXVFTUhKT2kxK0lsZFBvNjZGK1pIbnYvNEM5CjdUVzV5b3Ryb0t0SmNNOXFCV3FNVkhmZktpOENLQVZ4Szl5N05VekpKdVFDZVFZOU1wZ3p6d2QwdXpXREozaUsKR2E3NnFvZmVIaUpER3F2dko3RTluWENibHArZjBXK2VwK2prVWcxc2U1c0UrbXJnRTFUYmIxaWhMbXk2NnhlNwpnUGZTbEdBTjJWdjcxQ2tHM3BRdHVoK0h2ZXlKK3lXTkFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQi93UUVBd0lDCnBEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVZScW8rRVZYeUo0R0wKbDFPWXoyayt2cFlWVHp0RzkyN0dLYlNQUFZ0eS8yQUdZUkprck0vd1d2K2NsU2tMZkJyNmtwUjJTS0Z3TzdHNwpMRVplQWZ0WHZ3Ym1wT21MOWI5OUpOZmN0ak1EMVpjSGJhZ1NGM1l1czRKM3lSdzFhSnlmSnVOSDJLOUQwb1FHCm5JZ3dCc0ZjekwrVElrNUNBN1IyaFN3WlNkWkMvMlhZWUNicFh6ZGU4TVBCSGVXOXBzRDZseXhZbjRsSjMvQkgKYkNNakJnNWxCYlpoek5ZYWFWWUN4ZVlxYVNUWG11c3d4S0xqdCtvbnBzazJTR240WHhNVW9xdEYzTEgyVHc5Ywphb0ljaFVZbHJQcEFIYmlTODgwZVFIWXlJNGU2Z1ZsRVZoWnZzbDNZeGF0RG9ncm50YzhIbnBxK2xQbUNFSWZZCnR6ak1zTE5FCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    Service:
      Name:        pravega-upgrade-webhook-svc
      Namespace:   default
      Path:        /mutate-pravegaclusters
  Failure Policy:  Ignore
  Name:            upgradepravegaclusters.pravega.io
  Namespace Selector:
  Rules:
    API Groups:
      pravega.pravega.io
    API Versions:
      v1alpha1
    Operations:
      CREATE
      UPDATE
    Resources:
      pravegaclusters
  Side Effects:  Unknown
Events:          <none>
```

**Comment by EronWright** [comment]
It looks good.  Honestly the term 'upgrade' doesn't quite belong, since the webhook assumedly does general resource validation, default value assignment, and more beyond pure upgrade.

**Comment by pbelgundi** [comment]
> term 'upgrade' doesn't quite belong, since the webhook assumedly does general resource validation, default value assignment, and more beyond pure upgrad

Removed the term 'upgrade' from webhook , webhook-config and svc names.

**Pull request merged**
