### PR TITLE
Support for custom storage class

### PR DESCRIPTION
**Pull request by nikolay-t**
### Change log description

We need to install Pravega on bare-metal platform that does not have "standard" storage class. Instead, it has different storage class for Pravega. This change supports custom storage class.

### Purpose of the change

Requirement to set different storage class for Pravega.

### What the code does

Helm chart changes to support custom storage class.

### How to verify it

Execute helm installation with different, non-default storage class.

### CODE REVIEW

**Comment by pbelgundi** [comment]
Could you please also explain how this change was tested.

**Comment by nikolay-t** [comment]
> 
> 
> LGTM. Except that Travis build is failing, could you please check why.

Travis failed due to failure of following command: "aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID". Seems like $AWS_ACCESS_KEY_ID is not provided, and in general it looks like testing environment is not properly set. Anyway this is unknown reason for me, and does not seem to be related to the change in this PR.

**Comment by nikolay-t** [comment]
> 
> 
> > LGTM. Except that Travis build is failing, could you please check why.
> 
> Travis failed due to failure of following command: "aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID". Seems like $AWS_ACCESS_KEY_ID is not provided, and in general it looks like testing environment is not properly set. Anyway this is unknown reason for me, and does not seem to be related to the change in this PR.

I tried to check other open and closed PRs, and it seems like Travis didn't work for all of them.

**Comment by RaulGracia** [comment]
@pbelgundi is there an issue associated to this PR?

**Pull request merged**
