### PR TITLE
Issue 166: Add Client-Server TLS support

### LINKED ISSUE #166: Storing TLS objects as Kubernetes secrets and Distributing them to Pravega pods as files
**Background:**
Kubernetes supports an option to store and distribute sensitive data to containers, via the [Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) object. You first create a secret object (using `kubectcl`, yaml, etc.), and then pass the entries to the containers in the form of either environment variables or files in a volume. See an example in action, [here](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/).

When deploying a Pravega cluster with TLS enabled for Controllers and Segment Store pods, admins need to be able to distribute externally created TLS material to the containers/pods. Such material includes:
* X.509 certificates
* Cryptographic keys
* File containing the password of the key file
* Keystore (jks)
* Truststore (jks)
* PasswordAuthHandler input file

Kubernetes [Secret](https://kubernetes.io/docs/concepts/configuration/secret/)  object fits the bill rather nicely, both for keeping the TLS material safe and for distributing it to the pods. Currently, Pravega operator does not support using Secrets (It supports ConfigMap though, which is quite similar to the Secret object). 

**Requirement:**

The ask is to build support for creating Kubernetes Secret objects and distributing them to Pravega containers through volumes. The admin shall provide definitions for one or more secret objects in the Pravega cluster definition file. Pravega operator, which consumes the definition file, shall automatically create those secret objects and expose the entries in the objects as files on the volume with specified mount-paths. [This](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/) example in Kubernetes documentation illustrates its working. 

**More Details:**
Here's roughly how things should roughly work:

1. The admin creates Secret object(s) using commands like these (or alternatively, through yaml spec).

```bash
# Create a secret object called "controller-pki" with entries tlsCertFile, cacert, etc. 
# The values (such as ./controller01.pem) are path on the local file system.
$ kubectl create secret generic controller-pki \
        --from-file=tlsCertFile=./controller01.pem \
        --from-file=cacert=./ca-cert \
        --from-file=tlsKeyFile=./controller01.key.pem \
        --from-file=tlsKeyStoreFile=./controller01.jks \
        --from-file=passwordfile=./password 

# Create another one for segment stores.
$ kubectl create secret generic segmentstore-pki \
        --from-file=tlsCertFile=./segmentstore01.pem \
	--from-file=cacert=./ca-cert \
	--from-file=tlsKeyFile=./segmentstore01.key.pem
```

2. In the Pravega cluster definition file (`pravega.yaml` for example), the admin specifies the name and entries of the secret objects created in step 1. They also specify the mount-path of the secret object (such as `/etc/secret-volume`). Alternatively, we can fix the name of the objects and entries, so this step will not be needed. That'll limit the flexibility in introducing new secrets but still meet the current requirements.

The admin uses TLS file paths relative to the mount-path in the pravega cluster definition file to specify JVM system properties for the Pravega pod as shown below:
```yaml
pravega:
   ...
   options:
       options:
           controller.auth.tlsEnabled: "true"
           controller.auth.tlsCertFile: "/etc/secret-volume/controller01.pem"
           controller.auth.tlsKeyFile: "/etc/secret-volume/controller01.key.pem"
           ...
```

3. The admin executes the command to initiate the deployment. The Pravega operator system creates a volume at the specified mount path for each secret object, and makes the entries available as files in that volume. A corresponding pod definition snippet is shown below. 

```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: ...
      image: ...
      volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
```
The JVM system properties passed to the container will now automatically resolve file paths in volumes created for the secret (for example: `... -Dcontroller.auth.tlsCertFile: "/etc/secret-volume/controller01.pem" -Dcontroller.auth.tlsKeyFile: "/etc/secret-volume/controller01.key.pem ..."`). 

In effect, the admin is able to inject externally created TLS files into Pravega pods in a safe and secure manner.

### PR DESCRIPTION
**Pull request by Tristan1900**
### Change log description

- Add client-server support for TLS communication
- Ability to pass sensible files (certificates, passwords, truststores, etc) to Controller and Segment Store pods via Kubernetes `Secret`s

### Purpose of the change

Fix #166

### How to test the change

Tests should pass

### CODE REVIEW

**Comment by adrianmo** [comment]
@ravisharda can you please test the TLS changes?

**Comment by ravisharda** [comment]
I've verified that this feature is working! 

1. Here's how I created the secrets (one object each for controllers and segment stores): 
```
$ kubectl create secret generic controller-tls \
        --from-file=controllerTlsCertFile=./controller01.pem \
	--from-file=controllerCacert=./ca-cert \
	--from-file=controllerTlsKeyFile=./controller01.key.pem \
	--from-file=controllerTlsKeyStoreFile=./controller01.jks \
	--from-file=passwordfile=./password 

$ kubectl create secret generic segmentstore-tls \
      --from-file=segmentstoreTlsCertFile=./segmentstore01.pem \
      --from-file=segmentstoreCacert=./ca-cert \
      --from-file=segmentstoreTlsKeyFile=./segmentstore01.key.pem
```

2. Then, I specified the names of the two secrets objects under `spec` in the Pravega cluster manifest as follows, before creating the cluster:

```
 tls:
    static:
      controllerSecret: "controller-tls"
      segmentStoreSecret: "segmentstore-tls"
```

3. After the Pravega cluster came up, the keys used in the secrets objects were available as files under the mounted `/etc/secret-volume`, as shown below:

*Segment store pod:*
```bash
/etc/secret-volume # ls
segmentstoreCacert       segmentstoreTlsCertFile  segmentstoreTlsKeyFile
```

*Controller pod:*
```bash
/etc/secret-volume # ls
controllerCacert           controllerTlsCertFile      controllerTlsKeyFile       controllerTlsKeyStoreFile  passwordfile
```

**Comment by Tristan1900** [comment]
LGTM!

**Comment by EronWright** [comment]
I'm surprised that the platform team wasn't invited to review this feature, since they're the natural consumers of it.

**Comment by Tristan1900** [comment]
@EronWright Sorry about that, I thought this issue is brought up by the test team and I didn't think of the consumers back then. We will remember to add the platform team as reviewers in the future if new features are related. Meanwhile, please feel free to open issues if they are uncomfortable with the current API. Thanks!

**Comment by fpj** [comment]
@EronWright if you look at the changes, all it is doing is align the configuration of TLS of the operator with the one that Pravega exposes, there is no major architectural implication. In general, you should feel free to track this queue and chime in accordingly in the case there is anything that is particularly interesting and we miss it.

**Pull request merged**
